-module(ws_handler).

-export([init/2]).
-export([websocket_init/1]).
-export([websocket_handle/2]).
-export([websocket_info/2]).

init(Req, Opts) ->
	{cowboy_websocket, Req, Opts}.

websocket_init(State) ->
	erlang:start_timer(1000, self(), <<"Hello!">>),
	{ok, State}.

websocket_handle({text, Msg}, State) ->
	{reply, {text, << "That's what she said! ", Msg/binary >>}, State};
websocket_handle(_Data, State) ->
	{ok, State}.


-record(webhook, {
	id :: kz_term:api_ne_binary() | '_'
	,uri :: kz_term:api_ne_binary() | '_'
	,http_verb = 'get' :: http_verb() | '_'
	,hook_event :: kz_term:api_ne_binary() | '_' | '$1' | '$2'
	,hook_id :: kz_term:api_ne_binary() | '_'
	,retries = 3 :: hook_retries() | '_'
	,account_id :: kz_term:api_ne_binary() | '_' | '$1'
	,include_subaccounts = 'false' :: boolean() | '_' | '$3'
	,include_loopback = 'true' :: boolean() | '_'
	,custom_data :: kz_term:api_object() | '_'
	,modifiers :: kz_term:api_object() | '_'
}).

websocket_info({timeout, _Ref, Msg}, State) ->
	erlang:start_timer(1000, self(), <<"How' you doin'?">>),
	{reply, {text, Msg}, State};
websocket_info(_Info, State) ->
	{ok, State},


ets:foldl(fun(#webhook{custom_data={DataList}}=Webhook, Acc) -> case lists:keyfind(<<"action">>,1,DataList)=={<<"action">>,<<"play">>} of 'true' -> [Webhook | Acc]; 'false' -> Acc end end , [], webhook_listener),

	ets:foldl(fun(Webhook, Acc) -> io:format("WH=~p\nAcc=~p\n",[Webhook,Acc]) end , [], webhook_listener).

ets:foldl(fun(#webhook{custom_data=Data}=Webhook, Acc) -> case is_list({DataList}=Data), lists:keyfind(<<"action">>,1,DataList)=={<<"action">>,<<"play">>} of 'true' -> [Webhook | Acc]; 'false' -> Acc end end , [], webhooks_listener).
ets:foldl(fun(#webhook{custom_data=Data}=Webhook, Acc) -> case Data of undefined->io:format("Wrang type\n"); {_}-> {DataList}=Data, io:format("WH=~p\nAcc=~p\nDataList=~p\n",[Webhook,Acc,DataList]) end end , [], webhooks_listener).

Context={
	cb_context,
	[{to_json,[{<<"application">>,<<"json">>},{<<"application">>,<<"x-json">>}]}],
	[],
	[<<"GET">>,<<"POST">>,<<"PUT">>,<<"DELETE">>,<<"HEAD">>,<<"PATCH">>,<<"OPTIONS">>],
	[<<"PATCH">>,<<"PUT">>,<<"GET">>],
	[<<"en">>,<<"en-us">>,<<"en-gb">>],
	[<<"iso-8859-1">>],
	[<<"gzip;q=1.0">>,<<"identity;q=0.5">>],
	undefined,
	'x-auth-token',
	undefined,
	undefined,
	<<"GET">>,
	[{<<"webhooks">>,[]}],
	{[]},
	[],
	{[]},
	#{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"cache-control">> => <<"no-cache">>,<<"connection">> => <<"keep-alive">>, <<"content-type">> => <<"application/json">>, <<"host">> => <<"127.0.0.1:8000">>,	<<"postman-token">> =><<"04738665-5fea-449f-90ab-5dc5202241fe">>,<<"user-agent">> => <<"PostmanRuntime/7.1.1">>},
	{[]},
	undefined,
	undefined,
	undefined,
	undefined,
	undefined,
	<<"account%2Fea%2F57%2Fae4f45693dccd0a55f254226d6de">>,
	[{[{<<"_id">>,<<"object">>},
		{<<"_rev">>,<<"1-fd0f61b19fa2b8a472dbac201e6bc8c3">>},
		{<<"name">>,<<"Object">>},
		{<<"description">>,
		<<"Receive notifications when objects (like JSON document objects) in Kazoo are changed">>},
		{<<"modifiers">>,
		{[{<<"type">>,
		{[{<<"type">>,<<"array">>},
		{<<"description">>,
		<<"A list of object types to handle">>},
		{<<"items">>,
		[<<"account">>,<<"callflow">>,<<"device">>,
		<<"faxbox">>,<<"media">>,<<"user">>,
		<<"vmbox">>,<<"fax">>,<<"mailbox_message">>,
		<<"call_recording">>]}]}},
		{<<"action">>,
		{[{<<"type">>,<<"array">>},
		{<<"description">>,
		<<"A list of object actions to handle">>},
		{<<"items">>,
		[<<"doc_created">>,<<"doc_edited">>,
		<<"doc_deleted">>]}]}}]}},
		{<<"pvt_account_id">>,
		<<"ea57ae4f45693dccd0a55f254226d6de">>},
		{<<"pvt_account_db">>,
		<<"account%2Fea%2F57%2Fae4f45693dccd0a55f254226d6de">>},
		{<<"pvt_created">>,63683224260},
		{<<"pvt_modified">>,63683224260},
		{<<"pvt_type">>,<<"webhook_meta">>},
		{<<"pvt_node">>,<<"kazoo_apps@sergio.ttdev.ru">>},
		{<<"pvt_document_hash">>,
		<<"59af05978007298c94be079cef0454fb">>}]},
		{[{<<"_id">>,<<"notifications">>},
		{<<"_rev">>,<<"1-4197ec1809c0b2d4fc2a1fda9d883eaf">>},
		{<<"name">>,<<"Notifications Webhook">>},
		{<<"description">>,
		<<"Fire a webhook when a notification event is triggered in Kazoo">>},
		{<<"modifiers">>,
		{[{<<"type">>,
		{[{<<"type">>,<<"object">>},
		{<<"items">>,
		{[{<<"webhook">>,
		{[{<<"friendly_name">>,
		<<"Callflow Webhook Triggered">>},
		{<<"description">>,
		<<"This event is triggered when a corresponding webhook action in a callflow is reached">>}]}},
		{<<"voicemail_saved">>,
		{[{<<"friendly_name">>,
		<<"Voicemail Message Saved">>},
		{<<"description">>,
		<<"This event is triggered any time a voicemail message is saved in the voicemail box 'new' folder">>}]}},
		{<<"voicemail_new">>,
		{[{<<"friendly_name">>,
		<<"New Voicemail Message">>},
		{<<"description">>,
		<<"This event is triggered any time a voicemail message is left">>}]}},
		{<<"voicemail_full">>,
		{[{<<"friendly_name">>,
		<<"Voicemail Box Full">>},
		{<<"description">>,
		<<"This event is triggered any time an attempt to leave a voicemail message is blocked because the voicemail box is full">>}]}},
		{<<"transaction">>,
		{[{<<"friendly_name">>,
		<<"Transaction Completed">>},
		{<<"description">>,
		<<"This event is triggered when a transaction is attempted">>}]}},
		{<<"topup">>,
		{[{<<"friendly_name">>,
		<<"Automatic Account Top-up">>},
		{<<"description">>,
		<<"This event is triggered when an account automatic top-up is attempted">>}]}},
		{<<"service_added">>,
		{[{<<"friendly_name">>,<<"Service Added">>},
		{<<"description">>,
		<<"This event is triggered when an account's billable quantities change">>}]}},
		{<<"register">>,
		{[{<<"friendly_name">>,<<"Registration">>},
		{<<"description">>,
		<<"This event is triggered when a device registers but is not currently registered">>}]}},
		{<<"ported">>,
		{[{<<"friendly_name">>,<<"Ported">>},
		{<<"description">>,
		<<"This event is triggered when a port request for number is completed">>}]}},
		{<<"port_unconfirmed">>,
		{[{<<"friendly_name">>,
		<<"Port Unconfirmed">>},
		{<<"description">>,
		<<"This event is triggered when a port is created, prior to submitting">>}]}},
		{<<"port_scheduled">>,
		{[{<<"friendly_name">>,<<"Port Scheduled">>},
		{<<"description">>,
		<<"This event is triggered when a port is accepted by a carrier and scheduled">>}]}},
		{<<"port_request">>,
		{[{<<"friendly_name">>,<<"Port Request">>},
		{<<"description">>,
		<<"This event is triggered when a port is submitted for processing">>}]}},
		{<<"port_rejected">>,
		{[{<<"friendly_name">>,<<"Port Rejected">>},
		{<<"description">>,
		<<"This event is triggered when a port request is rejected">>}]}},
		{<<"port_pending">>,
		{[{<<"friendly_name">>,<<"Port Pending">>},
		{<<"description">>,
		<<"This event is triggered when a port request is accepted and submitted to a carrier">>}]}},
		{<<"port_comment">>,
		{[{<<"friendly_name">>,<<"Port Comment">>},
		{<<"description">>,
		<<"This event is triggered when a comment is left on a port request">>}]}},
		{<<"port_cancel">>,
		{[{<<"friendly_name">>,<<"Port Cancel">>},
		{<<"description">>,
		<<"This event is triggered when a port request is canceled">>}]}},
		{<<"password_recovery">>,
		{[{<<"friendly_name">>,
		<<"Password Recovery">>},
		{<<"description">>,
		<<"This event is triggered when an end user requests a password recovery link">>}]}},
		{<<"outbound_smtp_fax_error">>,
		{[{<<"friendly_name">>,
		<<"Invalid Email-to-Fax Email">>},
		{<<"description">>,
		<<"This event is triggered when the received email-to-fax email is invalid">>}]}},
		{<<"outbound_fax_error">>,
		{[{<<"friendly_name">>,
		<<"Fax Transmission Error">>},
		{<<"description">>,
		<<"This event is triggered when transmitting a fax fails">>}]}},
		{<<"outbound_fax">>,
		{[{<<"friendly_name">>,
		<<"Successful Fax Transmission">>},
		{<<"description">>,
		<<"This event is triggered when a fax is successfully transmitted">>}]}},
		{<<"new_user">>,
		{[{<<"friendly_name">>,<<"New User">>},
		{<<"description">>,
		<<"This event is triggered when an end user creates a new user">>}]}},
		{<<"new_account">>,
		{[{<<"friendly_name">>,<<"New Account">>},
		{<<"description">>,
		<<"This event is triggered when an end user creates a new account">>}]}},
		{<<"missed_call">>,
		{[{<<"friendly_name">>,<<"Missed Call">>},
		{<<"description">>,
		<<"This event is triggered when an corresponding missed call action in a callflow is invoked">>}]}},
		{<<"low_balance">>,
		{[{<<"friendly_name">>,
		<<"Account Low Balance">>},
		{<<"description">>,
		<<"This event is triggered when an account is found with a balance below the notification threshold">>}]}},
		{<<"inbound_fax_error">>,
		{[{<<"friendly_name">>,
		<<"Fax Reception Error">>},
		{<<"description">>,
		<<"This event is triggered when receiving a fax fails">>}]}},
		{<<"inbound_fax">>,
		{[{<<"friendly_name">>,
		<<"Successful Fax Reception">>},
		{<<"description">>,
		<<"This event is triggered when a fax is successfully received">>}]}},
		{<<"first_occurrence">>,
		{[{<<"friendly_name">>,
		<<"Account First Occurrence">>},
		{<<"description">>,
		<<"This event is triggered when an end user registers the first device and/or places the first call on an account">>}]}},
		{<<"deregister">>,
		{[{<<"friendly_name">>,<<"De-Registration">>},
		{<<"description">>,
		<<"This event is triggered when a device fails to re-register and the contact expires">>}]}},
		{<<"denied_emergency_bridge">>,
		{[{<<"friendly_name">>,
		<<"Emergency Call Failed">>},
		{<<"description">>,
		<<"This event is triggered when a call to an number classified as emergency fails">>}]}},
		{<<"customer_update">>,
		{[{<<"friendly_name">>,<<"Customer Update">>},
		{<<"description">>,
		<<"This event is triggered when the customer update API is used to deliver a message to the account">>}]}},
		{<<"cnam_request">>,
		{[{<<"friendly_name">>,<<"CNAM Update">>},
		{<<"description">>,
		<<"This event is triggered when an end user would like the CNAM for a number changed">>}]}},
		{<<"all">>,
		{[{<<"friendly_name">>,<<"All">>},
		{<<"description">>,
		<<"This event is triggered for any notification events">>}]}},
		{<<"account_zone_change">>,
		{[{<<"friendly_name">>,
		<<"Account Zone Change">>},
		{<<"description">>,
		<<"This event is triggered when an end user requests the home zone of an account is changed">>}]}}]}}]}}]}},
		{<<"pvt_account_id">>,
		<<"ea57ae4f45693dccd0a55f254226d6de">>},
		{<<"pvt_account_db">>,
		<<"account%2Fea%2F57%2Fae4f45693dccd0a55f254226d6de">>},
		{<<"pvt_created">>,63683224260},
		{<<"pvt_modified">>,63683224260},
		{<<"pvt_type">>,<<"webhook_meta">>},
		{<<"pvt_node">>,<<"kazoo_apps@sergio.ttdev.ru">>},
		{<<"pvt_document_hash">>,
		<<"526840e95e90c4ad474f1a11a00cb5fd">>}]},
		{[{<<"_id">>,<<"conference_mute">>},
		{<<"_rev">>,<<"1-3b5c68b992cb18965fd56ee9a2860682">>},
		{<<"name">>,<<"Conference mute">>},
		{<<"description">>,
		<<"This webhook is triggered when a on the command \"mute\" in any active conference">>},
		{<<"pvt_account_id">>,
		<<"ea57ae4f45693dccd0a55f254226d6de">>},
		{<<"pvt_account_db">>,
		<<"account%2Fea%2F57%2Fae4f45693dccd0a55f254226d6de">>},
		{<<"pvt_created">>,63686852244},
		{<<"pvt_modified">>,63686852244},
		{<<"pvt_type">>,<<"webhook_meta">>},
		{<<"pvt_node">>,<<"kazoo_apps@sergio.ttdev.ru">>},
		{<<"pvt_document_hash">>,
		<<"af1da6514c73b194cd96777458377949">>}]},
		{[{<<"_id">>,<<"conference_enter">>},
		{<<"_rev">>,<<"1-ef2a16863e534829dd0c875cd8dd3355">>},
		{<<"name">>,<<"Conference Enter">>},
		{<<"description">>,
		<<"This webhook is triggered when a participant entered in the conference">>},
		{<<"pvt_account_id">>,
		<<"ea57ae4f45693dccd0a55f254226d6de">>},
		{<<"pvt_account_db">>,
		<<"account%2Fea%2F57%2Fae4f45693dccd0a55f254226d6de">>},
		{<<"pvt_created">>,63685722894},
		{<<"pvt_modified">>,63685722894},
		{<<"pvt_type">>,<<"webhook_meta">>},
		{<<"pvt_node">>,<<"kazoo_apps@sergio.ttdev.ru">>},
		{<<"pvt_document_hash">>,
		<<"7953b720ef61db8e05426b883f15a321">>}]},
		{[{<<"_id">>,<<"conference_create">>},
		{<<"_rev">>,<<"1-bff9cb328960a1a8399eff0b30cf137a">>},
		{<<"name">>,<<"Conference create">>},
		{<<"description">>,
		<<"This webhook is triggered when the conference created by first participant">>},
		{<<"pvt_account_id">>,
		<<"ea57ae4f45693dccd0a55f254226d6de">>},
		{<<"pvt_account_db">>,
		<<"account%2Fea%2F57%2Fae4f45693dccd0a55f254226d6de">>},
		{<<"pvt_created">>,63686851594},
		{<<"pvt_modified">>,63686851594},
		{<<"pvt_type">>,<<"webhook_meta">>},
		{<<"pvt_node">>,<<"kazoo_apps@sergio.ttdev.ru">>},
		{<<"pvt_document_hash">>,
		<<"0afaa7d32ab43c86e77d14431b151035">>}]},
		{[{<<"_id">>,<<"conference_command">>},
		{<<"_rev">>,<<"8-98a66c6007f3315854aee3a955d9bc62">>},
		{<<"pvt_type">>,<<"webhook_meta">>},
		{<<"pvt_node">>,<<"kazoo_apps@sergio.ttdev.ru">>},
		{<<"pvt_modified">>,63687103747},
		{<<"pvt_document_hash">>,
		<<"0f5bb5b77ec4028326d5bdd54fb552f5">>},
		{<<"pvt_created">>,63687099928},
		{<<"pvt_account_id">>,
		<<"ea57ae4f45693dccd0a55f254226d6de">>},
		{<<"pvt_account_db">>,
		<<"account%2Fea%2F57%2Fae4f45693dccd0a55f254226d6de">>},
		{<<"name">>,<<"Conference command">>},
		{<<"modifiers">>,
		{[{<<"type">>,
		{[{<<"type">>,<<"array">>},
		{<<"ids">>,[]},
		{<<"description">>,
		<<"A list of conferences ids to handle">>}]}},
		{<<"action">>,
		{[{<<"type">>,<<"array">>},
		{<<"items">>,
		[<<"play">>,<<"mute">>,<<"deaf">>,<<"kick">>]},
		{<<"description">>,
		<<"A list of conference commands to handle">>}]}}]}},
		{<<"description">>,
		<<"This webhook is triggered on command in the specified conference">>}]},
		{[{<<"_id">>,<<"channel_destroy">>},
		{<<"_rev">>,<<"1-88b97ffa64bdc53413859f72e1f326cb">>},
		{<<"name">>,<<"Channel Destroy">>},
		{<<"description">>,
		<<"This webhook is triggered when a channel is destroyed, usually as a result of a hangup">>},
		{<<"pvt_account_id">>,
		<<"ea57ae4f45693dccd0a55f254226d6de">>},
		{<<"pvt_account_db">>,
		<<"account%2Fea%2F57%2Fae4f45693dccd0a55f254226d6de">>},
		{<<"pvt_created">>,63683224260},
		{<<"pvt_modified">>,63683224260},
		{<<"pvt_type">>,<<"webhook_meta">>},
		{<<"pvt_node">>,<<"kazoo_apps@sergio.ttdev.ru">>},
		{<<"pvt_document_hash">>,
		<<"db165a3dd74b1574b249c7c9a4d52b11">>}]},
		{[{<<"_id">>,<<"channel_create">>},
		{<<"_rev">>,<<"1-bc05a95d7f718077161080d3bf88e71a">>},
		{<<"name">>,<<"Channel Create">>},
		{<<"description">>,
		<<"This webhook is triggered when a new channel is created">>},
		{<<"pvt_account_id">>,
		<<"ea57ae4f45693dccd0a55f254226d6de">>},
		{<<"pvt_account_db">>,
		<<"account%2Fea%2F57%2Fae4f45693dccd0a55f254226d6de">>},
		{<<"pvt_created">>,63683224260},
		{<<"pvt_modified">>,63683224260},
		{<<"pvt_type">>,<<"webhook_meta">>},
		{<<"pvt_node">>,<<"kazoo_apps@sergio.ttdev.ru">>},
		{<<"pvt_document_hash">>,
		<<"b885609874a580f85891892638b70eda">>}]},
		{[{<<"_id">>,<<"channel_bridge">>},
		{<<"_rev">>,<<"1-d111c7bce47234b9050c39aa1365cfe1">>},
		{<<"name">>,<<"Channel Bridge">>},
		{<<"description">>,
		<<"This webhook is triggered when two channels are bridged together, such as two users/devices connected together">>},
		{<<"pvt_account_id">>,
		<<"ea57ae4f45693dccd0a55f254226d6de">>},
		{<<"pvt_account_db">>,
		<<"account%2Fea%2F57%2Fae4f45693dccd0a55f254226d6de">>},
		{<<"pvt_created">>,63683224260},
		{<<"pvt_modified">>,63683224260},
		{<<"pvt_type">>,<<"webhook_meta">>},
		{<<"pvt_node">>,<<"kazoo_apps@sergio.ttdev.ru">>},
		{<<"pvt_document_hash">>,
		<<"bc24512fa874c0e23f10a2e724911426">>}]},
		{[{<<"_id">>,<<"channel_answer">>},
		{<<"_rev">>,<<"1-da6a01f08af52adb8262b0a1ca93d83d">>},
		{<<"name">>,<<"Channel Answer">>},
		{<<"description">>,
		<<"This webhook is triggered when a channel establishes two-way audio, such as a voicemail box or the called party answering">>},
		{<<"pvt_account_id">>,
		<<"ea57ae4f45693dccd0a55f254226d6de">>},
		{<<"pvt_account_db">>,
		<<"account%2Fea%2F57%2Fae4f45693dccd0a55f254226d6de">>},
		{<<"pvt_created">>,63683224260},
		{<<"pvt_modified">>,63683224260},
		{<<"pvt_type">>,<<"webhook_meta">>},
		{<<"pvt_node">>,<<"kazoo_apps@sergio.ttdev.ru">>},
		{<<"pvt_document_hash">>,
		<<"3b887d356e66e2ed010202689bc79543">>}]},
		{[{<<"_id">>,<<"parking">>},
		{<<"_rev">>,<<"1-6e0982b9f15f3eb480e36fff0bfd04e2">>},
		{<<"name">>,<<"Call Parking">>},
		{<<"description">>,
		<<"Events when calls get parked/retrieved">>},
		{<<"pvt_account_id">>,
		<<"ea57ae4f45693dccd0a55f254226d6de">>},
		{<<"pvt_account_db">>,
		<<"account%2Fea%2F57%2Fae4f45693dccd0a55f254226d6de">>},
		{<<"pvt_created">>,63683224260},
		{<<"pvt_modified">>,63683224260},
		{<<"pvt_type">>,<<"webhook_meta">>},
		{<<"pvt_node">>,<<"kazoo_apps@sergio.ttdev.ru">>},
		{<<"pvt_document_hash">>,
		<<"8900098a63a053ce398c0151514f37a3">>}]}],
	false,
	{{1999,1,1},{0,0,0}},
	automatic,
	success,
	<<"init failed">>,
	500,
	<<>>,
	[{[{<<"name">>,<<"Object">>},
		{<<"description">>,
		<<"Receive notifications when objects (like JSON document objects) in Kazoo are changed">>},
		{<<"modifiers">>,
		{[{<<"type">>,
		{[{<<"type">>,<<"array">>},
		{<<"description">>,
		<<"A list of object types to handle">>},
		{<<"items">>,
		[<<"account">>,<<"callflow">>,<<"device">>,
		<<"faxbox">>,<<"media">>,<<"user">>,
		<<"vmbox">>,<<"fax">>,<<"mailbox_message">>,
		<<"call_recording">>]}]}},
		{<<"action">>,
		{[{<<"type">>,<<"array">>},
		{<<"description">>,
		<<"A list of object actions to handle">>},
		{<<"items">>,
		[<<"doc_created">>,<<"doc_edited">>,
		<<"doc_deleted">>]}]}}]}},
		{<<"id">>,<<"object">>}]},
		{[{<<"name">>,<<"Notifications Webhook">>},
		{<<"description">>,
		<<"Fire a webhook when a notification event is triggered in Kazoo">>},
		{<<"modifiers">>,
		{[{<<"type">>,
		{[{<<"type">>,<<"object">>},
		{<<"items">>,
		{[{<<"webhook">>,
		{[{<<"friendly_name">>,
		<<"Callflow Webhook Triggered">>},
		{<<"description">>,
		<<"This event is triggered when a corresponding webhook action in a callflow is reached">>}]}},
		{<<"voicemail_saved">>,
		{[{<<"friendly_name">>,
		<<"Voicemail Message Saved">>},
		{<<"description">>,
		<<"This event is triggered any time a voicemail message is saved in the voicemail box 'new' folder">>}]}},
		{<<"voicemail_new">>,
		{[{<<"friendly_name">>,
		<<"New Voicemail Message">>},
		{<<"description">>,
		<<"This event is triggered any time a voicemail message is left">>}]}},
		{<<"voicemail_full">>,
		{[{<<"friendly_name">>,
		<<"Voicemail Box Full">>},
		{<<"description">>,
		<<"This event is triggered any time an attempt to leave a voicemail message is blocked because the voicemail box is full">>}]}},
		{<<"transaction">>,
		{[{<<"friendly_name">>,
		<<"Transaction Completed">>},
		{<<"description">>,
		<<"This event is triggered when a transaction is attempted">>}]}},
		{<<"topup">>,
		{[{<<"friendly_name">>,
		<<"Automatic Account Top-up">>},
		{<<"description">>,
		<<"This event is triggered when an account automatic top-up is attempted">>}]}},
		{<<"service_added">>,
		{[{<<"friendly_name">>,<<"Service Added">>},
		{<<"description">>,
		<<"This event is triggered when an account's billable quantities change">>}]}},
		{<<"register">>,
		{[{<<"friendly_name">>,<<"Registration">>},
		{<<"description">>,
		<<"This event is triggered when a device registers but is not currently registered">>}]}},
		{<<"ported">>,
		{[{<<"friendly_name">>,<<"Ported">>},
		{<<"description">>,
		<<"This event is triggered when a port request for number is completed">>}]}},
		{<<"port_unconfirmed">>,
		{[{<<"friendly_name">>,
		<<"Port Unconfirmed">>},
		{<<"description">>,
		<<"This event is triggered when a port is created, prior to submitting">>}]}},
		{<<"port_scheduled">>,
		{[{<<"friendly_name">>,<<"Port Scheduled">>},
		{<<"description">>,
		<<"This event is triggered when a port is accepted by a carrier and scheduled">>}]}},
		{<<"port_request">>,
		{[{<<"friendly_name">>,<<"Port Request">>},
		{<<"description">>,
		<<"This event is triggered when a port is submitted for processing">>}]}},
		{<<"port_rejected">>,
		{[{<<"friendly_name">>,<<"Port Rejected">>},
		{<<"description">>,
		<<"This event is triggered when a port request is rejected">>}]}},
		{<<"port_pending">>,
		{[{<<"friendly_name">>,<<"Port Pending">>},
		{<<"description">>,
		<<"This event is triggered when a port request is accepted and submitted to a carrier">>}]}},
		{<<"port_comment">>,
		{[{<<"friendly_name">>,<<"Port Comment">>},
		{<<"description">>,
		<<"This event is triggered when a comment is left on a port request">>}]}},
		{<<"port_cancel">>,
		{[{<<"friendly_name">>,<<"Port Cancel">>},
		{<<"description">>,
		<<"This event is triggered when a port request is canceled">>}]}},
		{<<"password_recovery">>,
		{[{<<"friendly_name">>,
		<<"Password Recovery">>},
		{<<"description">>,
		<<"This event is triggered when an end user requests a password recovery link">>}]}},
		{<<"outbound_smtp_fax_error">>,
		{[{<<"friendly_name">>,
		<<"Invalid Email-to-Fax Email">>},
		{<<"description">>,
		<<"This event is triggered when the received email-to-fax email is invalid">>}]}},
		{<<"outbound_fax_error">>,
		{[{<<"friendly_name">>,
		<<"Fax Transmission Error">>},
		{<<"description">>,
		<<"This event is triggered when transmitting a fax fails">>}]}},
		{<<"outbound_fax">>,
		{[{<<"friendly_name">>,
		<<"Successful Fax Transmission">>},
		{<<"description">>,
		<<"This event is triggered when a fax is successfully transmitted">>}]}},
		{<<"new_user">>,
		{[{<<"friendly_name">>,<<"New User">>},
		{<<"description">>,
		<<"This event is triggered when an end user creates a new user">>}]}},
		{<<"new_account">>,
		{[{<<"friendly_name">>,<<"New Account">>},
		{<<"description">>,
		<<"This event is triggered when an end user creates a new account">>}]}},
		{<<"missed_call">>,
		{[{<<"friendly_name">>,<<"Missed Call">>},
		{<<"description">>,
		<<"This event is triggered when an corresponding missed call action in a callflow is invoked">>}]}},
		{<<"low_balance">>,
		{[{<<"friendly_name">>,
		<<"Account Low Balance">>},
		{<<"description">>,
		<<"This event is triggered when an account is found with a balance below the notification threshold">>}]}},
		{<<"inbound_fax_error">>,
		{[{<<"friendly_name">>,
		<<"Fax Reception Error">>},
		{<<"description">>,
		<<"This event is triggered when receiving a fax fails">>}]}},
		{<<"inbound_fax">>,
		{[{<<"friendly_name">>,
		<<"Successful Fax Reception">>},
		{<<"description">>,
		<<"This event is triggered when a fax is successfully received">>}]}},
		{<<"first_occurrence">>,
		{[{<<"friendly_name">>,
		<<"Account First Occurrence">>},
		{<<"description">>,
		<<"This event is triggered when an end user registers the first device and/or places the first call on an account">>}]}},
		{<<"deregister">>,
		{[{<<"friendly_name">>,<<"De-Registration">>},
		{<<"description">>,
		<<"This event is triggered when a device fails to re-register and the contact expires">>}]}},
		{<<"denied_emergency_bridge">>,
		{[{<<"friendly_name">>,
		<<"Emergency Call Failed">>},
		{<<"description">>,
		<<"This event is triggered when a call to an number classified as emergency fails">>}]}},
		{<<"customer_update">>,
		{[{<<"friendly_name">>,<<"Customer Update">>},
		{<<"description">>,
		<<"This event is triggered when the customer update API is used to deliver a message to the account">>}]}},
		{<<"cnam_request">>,
		{[{<<"friendly_name">>,<<"CNAM Update">>},
		{<<"description">>,
		<<"This event is triggered when an end user would like the CNAM for a number changed">>}]}},
		{<<"all">>,
		{[{<<"friendly_name">>,<<"All">>},
		{<<"description">>,
		<<"This event is triggered for any notification events">>}]}},
		{<<"account_zone_change">>,
		{[{<<"friendly_name">>,
		<<"Account Zone Change">>},
		{<<"description">>,
		<<"This event is triggered when an end user requests the home zone of an account is changed">>}]}}]}}]}}]}},
		{<<"id">>,<<"notifications">>}]},
		{[{<<"name">>,<<"Conference mute">>},
		{<<"description">>,
		<<"This webhook is triggered when a on the command \"mute\" in any active conference">>},
		{<<"id">>,<<"conference_mute">>}]},
		{[{<<"name">>,<<"Conference Enter">>},
		{<<"description">>,
		<<"This webhook is triggered when a participant entered in the conference">>},
		{<<"id">>,<<"conference_enter">>}]},
		{[{<<"name">>,<<"Conference create">>},
		{<<"description">>,
		<<"This webhook is triggered when the conference created by first participant">>},
		{<<"id">>,<<"conference_create">>}]},
		{[{<<"name">>,<<"Conference command">>},
		{<<"modifiers">>,
		{[{<<"type">>,
		{[{<<"type">>,<<"array">>},
		{<<"ids">>,[]},
		{<<"description">>,
		<<"A list of conferences ids to handle">>}]}},
		{<<"action">>,
		{[{<<"type">>,<<"array">>},
		{<<"items">>,
		[<<"play">>,<<"mute">>,<<"deaf">>,<<"kick">>]},
		{<<"description">>,
		<<"A list of conference commands to handle">>}]}}]}},
		{<<"description">>,
		<<"This webhook is triggered on command in the specified conference">>},
		{<<"id">>,<<"conference_command">>}]},
		{[{<<"name">>,<<"Channel Destroy">>},
		{<<"description">>,
		<<"This webhook is triggered when a channel is destroyed, usually as a result of a hangup">>},
		{<<"id">>,<<"channel_destroy">>}]},
		{[{<<"name">>,<<"Channel Create">>},
		{<<"description">>,
		<<"This webhook is triggered when a new channel is created">>},
		{<<"id">>,<<"channel_create">>}]},
		{[{<<"name">>,<<"Channel Bridge">>},
		{<<"description">>,
		<<"This webhook is triggered when two channels are bridged together, such as two users/devices connected together">>},
		{<<"id">>,<<"channel_bridge">>}]},
		{[{<<"name">>,<<"Channel Answer">>},
		{<<"description">>,
		<<"This webhook is triggered when a channel establishes two-way audio, such as a voicemail box or the called party answering">>},
		{<<"id">>,<<"channel_answer">>}]},
		{[{<<"name">>,<<"Call Parking">>},
		{<<"description">>,
		<<"Events when calls get parked/retrieved">>},
		{<<"id">>,<<"parking">>}]}],
#{},
{[{<<"page_size">>,11}]},
{1519,986109,392794},
<<"e58fee2c49278463792bdace991a4585">>,
[{has_qs_filter,false},
{view_direction,descending},
{is_superduper_admin,false},
{req,#{bindings => #{version => <<"v2">>},
body_length => 0,cert => undefined,
charset => undefined,has_body => false,
headers =>
#{<<"accept">> => <<"*/*">>,
<<"accept-encoding">> => <<"gzip, deflate">>,
<<"cache-control">> => <<"no-cache">>,
<<"connection">> => <<"keep-alive">>,
<<"host">> => <<"127.0.0.1:8000">>,
<<"postman-token">> =>
<<"04738665-5fea-449f-90ab-5dc5202241fe">>,
<<"user-agent">> =>
<<"PostmanRuntime/7.1.1">>},
host => <<"127.0.0.1">>,host_info => undefined,
language => <<"en">>,
media_type => {<<"application">>,<<"json">>,[]},
method => <<"GET">>,path => <<"/v2/webhooks">>,
path_info => [<<"webhooks">>],
peer => {{127,0,0,1},50146},
pid => <0.6217.0>,port => 8000,qs => <<>>,
ref => api_resource,
resp_headers =>
#{<<"content-language">> => <<"en">>,
<<"content-type">> =>
[<<"application">>,<<"/">>,<<"json">>,
<<>>],
<<"vary">> =>
[<<"accept-language">>,
[<<", ">>,<<"accept">>]],
<<"x-request-id">> =>
<<"e58fee2c49278463792bdace991a4585">>},
scheme => <<"http">>,
sock => {{127,0,0,1},8000},
streamid => 1,version => 'HTTP/1.1'}},
{metrics,{439,13760}}],
<<>>,8000,<<"/v2/webhooks">>,<<>>,<<"GET">>,
{[]},
<<"127.0.0.1">>,undefined,undefined,<<"v2">>,false,
undefined,<<"http://127.0.0.1:8000/v2/webhooks">>}
