PROJECT = web_show_message
PROJECT_DESCRIPTION = show test webhook message
PROJECT_VERSION = 1

DEPS += cowboy cowlib ranch
dep_cowboy = git https://github.com/ninenines/cowboy 2.2.0
dep_cowlib = git https://github.com/ninenines/cowlib 2.1.0
dep_ranch = git https://github.com/ninenines/ranch 1.4.0


include ../erlang.mk
