PROJECT = upload_files
PROJECT_DESCRIPTION = upload files for call recording
PROJECT_VERSION = 1

DEPS += cowboy cowlib ranch kazoo_stdlib
dep_cowboy = git https://github.com/ninenines/cowboy 2.2.0
dep_cowlib = git https://github.com/ninenines/cowlib 2.1.0
dep_ranch = git https://github.com/ninenines/ranch 1.4.0
dep_kazoo_stdlib = ln /home/serg/src/kazoo/core/kazoo_stdlib

include ../erlang.mk
